global:
  scrape_interval: 15s

scrape_configs:
  - job_name: node_exporter
    static_configs:
      - targets:
          - "10.0.0.4:9100"
          - "10.0.0.8:9100"
          - "10.0.0.10:9100"
        labels:
          environment: DEV
          region: EMEA

  - job_name: windows_exporter
    static_configs:
      - targets:
          - "10.0.0.6:9182"
          - "10.0.0.9:9182"
          - "10.0.0.7:9182"
        labels:
          environment: DEV
          region: EMEA

  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]  # Look for a HTTP 200 response.
    static_configs:
      - targets:
        - https://cariad.technology
        - https://azure.status.microsoft/en-us/status
        - https://capgemini.com
        - https://expired-rsa-dv.ssl.com
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 127.0.0.1:9115  # The blackbox exporter's real hostname:port.

  - job_name: 'blackbox_exporter'  # collect blackbox exporter's operational metrics.
    static_configs:
      - targets: ['127.0.0.1:9115']
